# Github repo path, modify based on your env
git_dir: /work/PRTNR/CHUV/DIR/rgottar1/spatial/Cluster_Benchmark/SpaceHack_CherryPick
# Dataset path, modify based on your env
dataset_dir: "/work/PRTNR/CHUV/DIR/rgottar1/spatial/Cluster_Benchmark/data"
datasets:
  - xenium-mouse-brain-SergioSalas       # Mouse Brain
  - STARmap_plus
  - abc_atlas_wmb_thalamus
  - libd_dlpfc                            # Visium Comparison
  - visium_breast_cancer_SEDR
  - visium_chicken_heart
#  - stereoseq_developing_Drosophila_embryos_larvae
#  - "stereoseq_mouse_embryo"

seed: 2023

# Methods to run for the pipeline, modify based on your need
use_methods:
############ Native Implementation Done ############
  - "BANKSY"
  - "CellCharter"
  - "DRSC"
  - "precast"
  - "SpaceFlow"
  - "scanpy"
  - "meringue"
  - "seurat"
  - "SEDR"            # memory or time consuming methods
  - "bass"
  - "stardust"
  - "STAGATE"
  - "spaGCN"
  - "GraphST"         # Only for Visium, stereoseq and slide-seq V2
  - "BayesSpace"      # Only for Visium
  - "SC_MEB"          # Only for Visium and ST

############ TODO Native ############
#  - "SpiceMix"      # Remaining implementation
#  - "maple"
#  - "SCAN-IT"
#  - "SOTIP"
#  - "Giotto"
#  - "spatialGE"
#  - "conST"

############ Implementation Error ############
#  - "DeepST"         # Import error


