# Github repo path, modify based on your env
git_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/workflow/SpaceHack2023
# Dataset path, modify based on your env
dataset_dir: /home/jovyan/scratch/SpaceHack2/userfolders/jsun/workflow/pca_test/

n_pcs: "35"
visualization: true
seed: 2023

neighbors_infos:
  delaunay_triangulation:
    script: preprocessing/neighbors/delaunay_triangulation/delaunay_triangulation.py
    env: preprocessing/neighbors/delaunay_triangulation/delaunay_triangulation.yml

use_datasets:
#  - "abc_atlas_wmb_thalamus"           # neighbor network wrong
  - "libd_dlpfc"
#  - "mouse_brain_sagittal_anterior"
#  - "mouse_brain_sagittal_posterior"
#  - "mouse_kidney_coronal"
#  - "osmfish_Ssp"           # only 13 features, 20 pca too much
#  - "sotip_simulation"
#  - "spatialDLPFC"
#  - "visium_breast_cancer_SEDR"
#  - "visium_chicken_heart"


#  - "xenium-mouse-brain-SergioSalas"    # Data unavail
#  - "xenium-breast-cancer"
#  - "SEA_AD_data"
#  - "STARmap-2018-mouse-cortex"